name: Push in branch main
on:
  push:
    branches: main

jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install dependencies
        run: npm ci

      - name: run tests
        run: (npx cypress run --e2e --browser chrome || true) && (npm run generateTxt)
